const fs = require("node:fs/promises")
const path = require("node:path")

const assetTypes = new Set([".html", ".js", ".css", ".json", ".svg", ".png", ".jpg", ".jpeg", ".webp", ".gif", ".ico", ".avif", ".glb", ".gltf", ".bin", ".ktx2", ".woff", ".woff2", ".ttf", ".otf", ".mp3", ".wav", ".ogg", ".mp4", ".webm", ".txt"])
const assetDirectories = ["assets", "isometric-room", "jev-country", "procedurally-fish-animation", "vintage-tv", "windy-grass"]
const marker = ".lab-static-build"
const markerText = "Generated by common/build-static.cjs\n"

async function buildStatic(root = path.resolve(__dirname, "..")) {
  const output = path.join(root, "dist")
  try {
    await fs.access(output)
    const owned = await fs.readFile(path.join(output, marker), "utf8").catch(() => "")
    if (owned !== markerText) throw new Error("Refusing to replace dist: it is not a generated lab build.")
    await fs.rm(output, { recursive: true })
  } catch (error) {
    if (error.code !== "ENOENT") throw error
  }
  await fs.mkdir(output, { recursive: true })
  await fs.writeFile(path.join(output, marker), markerText)
  for (const file of ["index.html", "robots.txt", "sitemap.xml"]) {
    await fs.copyFile(path.join(root, file), path.join(output, file))
  }
  async function copyAssets(relative) {
    const entries = await fs.readdir(path.join(root, relative), { withFileTypes: true })
    for (const entry of entries) {
      if (entry.name.startsWith(".") || entry.name === "demo" || entry.name === "node_modules") continue
      const source = path.join(relative, entry.name)
      if (entry.isDirectory()) await copyAssets(source)
      else if (entry.isFile() && assetTypes.has(path.extname(entry.name).toLowerCase()) && !/\.(?:test|spec)\.js$/i.test(entry.name)) {
        const destination = path.join(output, source)
        await fs.mkdir(path.dirname(destination), { recursive: true })
        await fs.copyFile(path.join(root, source), destination)
      }
    }
  }
  for (const directory of assetDirectories) {
    try { await copyAssets(directory) } catch (error) {
      if (error.code !== "ENOENT" || directory !== "windy-grass") throw error
    }
  }
  return output
}

if (require.main === module) {
  buildStatic().then(output => console.log(`Static site built in ${output}`)).catch(error => {
    console.error(error.message)
    process.exitCode = 1
  })
}

module.exports = { buildStatic }